### ISSUE TITLE
Bug: No toggles shown for dark/light mode on 2025.9b

### ISSUE THREAD

**Issue by TheFes** [piitaya/lovelace-mushroom-themes#60]
Since the 2025.9 beta all Mushroom templates do not show the toggles to switch between light and dark mode, and only seem to support light mode. 
See the video below which shows that the toggles disappear as soon as a Mushroom template is selected

https://github.com/user-attachments/assets/631c3294-7e10-49ed-90c1-9a9838f2ec69

**Comment by piitaya** [comment]
<img width="594" height="146" alt="Image" src="https://github.com/user-attachments/assets/5b9814ca-1b83-449c-87ec-097f4cd0f8a5" />

Hum, I can not reproduce on my system 🙃

**Comment by TheFes** [comment]
That's weird. I have it both on the companion app (last version) as on Chrome on my laptop.
Could it be an issue in combination with something else? Maybe kiosk mode? I will test that later on.

**Comment by fwmarcel** [comment]
Hey. I have the same problem, but not with the beta, but with the release.

**Comment by TheFes** [comment]
Well, it's not Kiosk mode. I installed the Mushroom themes on my nightly system, and as soon as it restarted after installing the theme in HACS, it was switched to light mode, without an option to change to dark mode again. 
Changing the setting from `Use default theme` to `Home Assistant` enabled the setting to set Dark Mode again.

This system has no custom cards or dashboard related custom components (like browser mod or Kiosk mode) installed.

**Comment by AarvdH** [comment]
Exactly the same problem, on several browsers testet and companion app on mobile phone and tablet.

**Comment by fireheadman** [comment]
same problem here too...  none of the mushroom theme offer the dark mode.

<img width="559" height="246" alt="Image" src="https://github.com/user-attachments/assets/c55180f8-cd50-4b4a-af1f-4f2c27966994" />

**Comment by TheFes** [comment]
@piitaya 
Not sure if this helps, but on the nightly I see this error message in the log

<img width="640" height="231" alt="Image" src="https://github.com/user-attachments/assets/7690bfb6-0a23-4dd9-ad90-6678c6139023" />

**Comment by piitaya** [comment]
https://github.com/piitaya/lovelace-mushroom-themes/blob/main/themes/mushroom.yaml

```yaml
# DO NOT EDIT THIS FILE.
# This file will be reset with updates.
# If you want to customize it, copy the content in another folder and file and change the name.
# https://www.home-assistant.io/integrations/frontend/#defining-themes
Mushroom:
    # Nothing here as it's the default HA theme since 2022.11
    modes:
        light: {}
        dark: {}
```

Do you have this theme in your theme folder? The keys are here. You are probably using an older version.

**Comment by TheFes** [comment]
For Mushroom Shadow this is what I have on both my production system (running 2025.9.3) and on my nightly system (running 2025.10.0.dev202509190235)

```yaml
# DO NOT EDIT THIS FILE.
# This file will be reset with updates.
# If you want to customize it, copy the content in another folder and file and change the name.
# https://www.home-assistant.io/integrations/frontend/#defining-themes
Mushroom Shadow:
    # Home Assistant override
    ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
    ha-card-border-width: 0
    modes:
        light: {}
        dark: {}
````
So, the keys are indeed there.

However, I still get this log message on the nightly
```
2025-09-19 11:53:55.848 ERROR (MainThread) [homeassistant.components.frontend] Theme Mushroom Shadow is invalid: must contain at least one of light, dark. for dictionary value @ data['modes']
2025-09-19 11:53:55.848 ERROR (MainThread) [homeassistant.components.frontend] Theme Mushroom Square Shadow is invalid: must contain at least one of light, dark. for dictionary value @ data['modes']
2025-09-19 11:53:55.848 ERROR (MainThread) [homeassistant.components.frontend] Theme Mushroom Square is invalid: must contain at least one of light, dark. for dictionary value @ data['modes']
2025-09-19 11:53:55.849 ERROR (MainThread) [homeassistant.components.frontend] Theme Mushroom is invalid: must contain at least one of light, dark. for dictionary value @ data['modes']
```

**Comment by TheFes** [comment]
With the update to the 2025.10 beta I now see the same error messages on my production system. It doesn't even show the theme in the dropdown anymore now.

**Comment by TheFes** [comment]
I've tested a bit, and it doesn't like the empty dict
When changed to this, it works fine
```yaml
# DO NOT EDIT THIS FILE.
# This file will be reset with updates.
# If you want to customize it, copy the content in another folder and file and change the name.
# https://www.home-assistant.io/integrations/frontend/#defining-themes
Mushroom Shadow:
  # Home Assistant override
  ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
  ha-card-border-width: 0
  modes:
    light:
      ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
      ha-card-border-width: 0
    dark:
      ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
      ha-card-border-width: 0
```

**Comment by piitaya** [comment]
May be it is caused by YAML indentation... I pushed an update with indentation change. Let's see if it works. 
It's hard to provide a fix as I don't have the issue on my side 😅

**Comment by TheFes** [comment]
the prettier extension removes the additional spaces when I save. But also when this is used it doesn't work
```yaml
# DO NOT EDIT THIS FILE.
# This file will be reset with updates.
# If you want to customize it, copy the content in another folder and file and change the name.
# https://www.home-assistant.io/integrations/frontend/#defining-themes
Mushroom Shadow:
  # Home Assistant override
  ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
  ha-card-border-width: 0
  modes:
    light: {}
    dark: {}
```
So I don't think the indentation is the issue. The 2 space indentation actually is shown as an error in VSCode (the indentation becomes red), but prettier still overrules it.

**Comment by TheFes** [comment]
Problem persists with the new version, so it was not indentation.
It really doesn't like the empty dicts.

**Comment by fireheadman** [comment]
got excited seeing an updated in HA for this.... but turned out not related to this issue.
Been missing the shadow and square themes in dark mode!

hope this gets resolved soon

**Comment by TheFes** [comment]
@fireheadman if you change them manually like I posted above, they will work again
For some reason HA doesn't accept the empty configuration for the light and dark team anymore.

**Comment by fireheadman** [comment]
thanks @TheFes 
and to expand on this....  (I used HassOS), so here is how/where to get to that file to modify it, which looks like it will get overwritten at some point.

Otherwise, it is nice to have my dark shadow theme back online!


**_ssh to the HASSOS server, then jump into the docker container_**
```
Welcome to Home Assistant OS.

Use `ha` to access the Home Assistant CLI.
# docker exec -it homeassistant /bin/bash
homeassistant:/config#
```

**_Now cd to the mushroom themes location and edit the yaml file_**
```
homeassistant:/config# cd themes/mushroom/
homeassistant:/config/themes/mushroom# cat mushroom-shadow.yaml
# DO NOT EDIT THIS FILE.
# This file will be reset with updates.
# If you want to customize it, copy the content in another folder and file and change the name.
# https://www.home-assistant.io/integrations/frontend/#defining-themes
Mushroom Shadow:
  # Home Assistant override
  ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
  ha-card-border-width: 0
  modes:
    light:
      ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
      ha-card-border-width: 0
    dark:
      ha-card-box-shadow: 0px 2px 4px 0px rgba(0,0,0,0.16)
      ha-card-border-width: 0
```

**_Restart HA, then select the shadow theme + dark mode = done_**

<img width="552" height="253" alt="Image" src="https://github.com/user-attachments/assets/0be3926e-f819-4d1e-8ea6-bfcebce72337" />

**Comment by TheFes** [comment]
@fireheadman you could've also used the File editor, or Visual Code Server add-on instead of using SSH.
And it will be overwritten if you install an update of the theme.

**Comment by fireheadman** [comment]
thanks, I know of those... but I keep a slim setup (minimal amount of addons) running on my ship.
